INSERT INTO "ESTAT"."V1"."mod_article_division" (id, label) VALUES (1, 'Excel');
INSERT INTO "ESTAT"."V1"."mod_article_division" (id, label) VALUES (2, 'Other articles');
INSERT INTO "ESTAT"."V1"."mod_article_division" (id, label) VALUES (3, 'Tables');
INSERT INTO "ESTAT"."V1"."mod_article_division" (id, label) VALUES (4, 'Database');
INSERT INTO "ESTAT"."V1"."mod_article_division" (id, label) VALUES (5, 'Dedicated Section');
INSERT INTO "ESTAT"."V1"."mod_article_division" (id, label) VALUES (6, 'Publications');
INSERT INTO "ESTAT"."V1"."mod_article_division" (id, label) VALUES (7, 'Methodology');
INSERT INTO "ESTAT"."V1"."mod_article_division" (id, label) VALUES (8, 'Legislation');
INSERT INTO "ESTAT"."V1"."mod_article_division" (id, label) VALUES (9, 'Visualisation');
INSERT INTO "ESTAT"."V1"."mod_article_division" (id, label) VALUES (10, 'External Link');