
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Population and migration');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Population');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('International Migration and Asylum');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Health');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Demography');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Energy');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Public health');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Labour market');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Education');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Crime and criminal justice');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Transport');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Banking, insurance, financial statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Agriculture statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Labour');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('WTO terminology');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('WHO terminology');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Waste statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Validation');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Urban statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('United Nations terminology');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('UNECE terminology');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('UN metadata terminology');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('UN - Geographic Information Systems');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('UN - Data editing terminology');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('U.S. Bureau of Labor Statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Tourism');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Time-use statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Temporal disaggregation');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('System of Environmental-Economic Accounting');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Survey sampling');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Structural statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Structural business statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Statistics Explained');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Statistical methodologies');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Statistical Data and Metadata Exchange');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Statistical concept; Peer reviews');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Statistical concept (2)');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Statistical concept');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Statistical agency organization');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Social statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('SNA 2008');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('SNA 1993');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('SNA');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Short-term statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Seasonal adjustment');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Science and technology statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Road transport');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Research and development');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Regional statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Regional and small area statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Regional accounts and indicators');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Railway transport');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('R & D - Oslo Manual');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Quarterly national accounts');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Quality; Peer reviews');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Quality, Implementation, Tools; Peer reviews');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Quality, Framework; Peer reviews');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Quality, Framework');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Quality, Evaluation, Assessments; Peer reviews');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Quality, Evaluation, Assessments');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Quality, Documentation, Measurement; Peer reviews');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Quality, Documentation, Measurement');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Quality, Description, Principles; Peer reviews');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Quality, Description, Principles');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Quality, Description, Criteria; Peer reviews');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Quality, Conformity');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Quality');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Purchasing power parities');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Public finance');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Producer price indices');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('PRODCOM');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Prices');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Postal statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Population censuses - UNECE');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Population censuses');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Pipeline transport');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Pesticides');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Pension funds');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Peer reviews');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Orchard statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('OECD terminology');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('OECD - Non-Observed Economy');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('OECD - Data and Metadata Reporting');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('OECD - Business tendency surveys');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('National accounts');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('NACE Rev. 1');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Migration statistics - UNO');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Migration statistics - ILO');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Migration statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Metadata');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Memobust Glossary');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Maritime transport');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Living conditions');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Land Use/Land Cover');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Land estimation');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Labour Force Survey');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Labour cost');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('International trade in services');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('International guidelines on statistical business registers');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('International accounting standards');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Insurance services');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Innovation');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Inland waterway transport');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Information society');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('IMF terminology');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('ILO terminology');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Housing price statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Harmonised indices of consumer prices');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Government finance, fiscal and public sector statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Globalisation');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Gesmes terminology');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Geographic Information Systems');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('General concept; Peer reviews');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('General concept');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Gender statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Frascati Manual 1993');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Frascati Manual');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Forestry');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Foreign direct investment');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Foreign AffiliaTes Stat. (FATS)');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Food: From farm to fork statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Food safety');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Fisheries');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Financial statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('FAO Agricultural censuses');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('External trade');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('External debt - IMF');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('EU-SILC');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Eurostat terminology');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('European System of Accounts (ESA)');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('European Statistics on persons and households');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('European Statistics Code of Practice');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('European Health Interview Survey (EHIS)');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('EU legislation');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('ESSPROS Manual');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('ESS guidelines; Peer reviews');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('ESS guidelines');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('ESA 1995');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Environment - EU legislation');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Environment');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Employment');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Education - ISCED');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Economic accounts for agriculture');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Economic accounts');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('ECB terminology');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Distributive trade');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Data protection');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Data and metadata exchange');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Customs terminology');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Culture');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Crop stat. - EU legislation');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Crime statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Consumer Price Index');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Community vineyard register');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Common Assessment Framework (CAF); Peer reviews');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Common Assessment Framework (CAF)');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Classifications');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Business statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Business registers');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Business demography');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Balance of Payments, IMF');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Balance of Payments, Eurostat');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Balance of payments');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Australian Bureau of Statistics');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Air transport');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Agriculture, forestry and fisheries');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Agriculture - EU legislation');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Agriculture');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('Administrative register');
INSERT INTO "ESTAT"."V1"."mod_ramon_category" (label) VALUES ('1993 Regulation on statistical units');

INSERT INTO "ESTAT"."V1"."mod_concept_type" (id, label) VALUES (1, 'TERM');
INSERT INTO "ESTAT"."V1"."mod_concept_type" (id, label) VALUES (2, 'VAR');

INSERT INTO "ESTAT"."V1"."mod_measurement_unit" (id, label) VALUES (1, 'Hectares');
INSERT INTO "ESTAT"."V1"."mod_measurement_unit" (id, label) VALUES (2, 'Number');
INSERT INTO "ESTAT"."V1"."mod_measurement_unit" (id, label) VALUES (3, 'Percentage');
INSERT INTO "ESTAT"."V1"."mod_measurement_unit" (id, label) VALUES (4, 'Inhabitants per square kilometer');
INSERT INTO "ESTAT"."V1"."mod_measurement_unit" (id, label) VALUES (5, 'Millions of Euro');
INSERT INTO "ESTAT"."V1"."mod_measurement_unit" (id, label) VALUES (6, 'Thousands of tonnes');

INSERT INTO "ESTAT"."V1"."mod_statistical_unit" (id, label) VALUES (0, 'Not applicable');
INSERT INTO "ESTAT"."V1"."mod_statistical_unit" (id, label) VALUES (1, 'Resident unit');
INSERT INTO "ESTAT"."V1"."mod_statistical_unit" (id, label) VALUES (2, 'Individuals');
INSERT INTO "ESTAT"."V1"."mod_statistical_unit" (id, label) VALUES (3, 'Households');
INSERT INTO "ESTAT"."V1"."mod_statistical_unit" (id, label) VALUES (4, 'Accidents');
INSERT INTO "ESTAT"."V1"."mod_statistical_unit" (id, label) VALUES (5, 'Agricultural Holdings and/or dairies');
INSERT INTO "ESTAT"."V1"."mod_statistical_unit" (id, label) VALUES (6, 'Geographical area');
INSERT INTO "ESTAT"."V1"."mod_statistical_unit" (id, label) VALUES (7, 'Enterprises (Corporations, Institutions)');
